config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => 'api/docs'
  mount Rswag::Api::Engine => '/api-docs'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #

  root  to: redirect("/activity_logs")

  resources :activity_logs, only: [:index]

  namespace :api do
    resources :activities, only: [:index]
    resources :babies, only: [:index] do
      get '/activity_logs' => 'activity_logs#index'
    end

    resources :activity_logs, only: [:create, :update]
  end

  get '*patch',  to: "application#not_found_page"
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :activity_logs

end

app/models/activity_log.rb
class ActivityLog < ApplicationRecord
  belongs_to :assistant
  belongs_to :activity
  belongs_to :baby

  validates :baby_id, :assistant_id, :activity_id, :start_time, presence: true
  validates :baby_id, :assistant_id, :activity_id, numericality: { only_integer: true }
  validates :stop_time, presence: true, on: :update

  before_update :set_duration

  validates :start_time, iso8601_date_time_utc: true, on: :create
  validates :stop_time, iso8601_date_time_utc: true, on: :update

  validate :stop_time_later_than_start_time, on: :update

  def stop_time_later_than_start_time
    if self.stop_time.nil? || self.start_time > self.stop_time
      errors.add(:stop_time, "can not be earlier than: #{self.start_time.iso8601}")
    end
  end

  def set_duration
    diff_in_seconds = self.stop_time.to_time - self.start_time.to_time

    diff_in_minutes = diff_in_seconds / 60

    self.duration = diff_in_minutes

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assistant.rb
class Assistant < ApplicationRecord
  has_many :activity_logs
end

app/models/baby.rb
class Baby < ApplicationRecord
  has_many :activity_logs

  def age
    diff = Date.today - self.birthday.to_date

    days = diff.to_i

    months = days / 30

    months
  end

end

app/controllers/activity_logs_controller.rb
class ActivityLogsController < ApplicationController


  # Todo list:
  # - Check months algorithm (Done)
  # - Remember applied filters on table (Done)
  # - Refactor as json on model (Done)
  # - Refactor time formatting as standard (Done)
  # - Verify is runnable on vagrant (Done)
  # - Update swagger docs (Done)
  def index
    @assistants = Assistant.all
    @babies = Baby.all
    @time_zone = "America/Monterrey"

    @activity_logs = ActivityLog.includes(:baby, :assistant, :activity).all

    @filters = filter_params

    if @filters[:baby_id].present?
      @activity_logs = @activity_logs.where(baby_id: @filters[:baby_id])
    end

    if @filters[:assistant_id].present?
      @activity_logs = @activity_logs.where(assistant_id: @filters[:assistant_id])
    end

    if @filters[:status].present?
      @activity_logs = @activity_logs.where(stop_time: nil) if @filters[:status] == "false"
      @activity_logs = @activity_logs.where.not(stop_time: nil) if @filters[:status] != "false"
    end

    @activity_logs = @activity_logs.order(start_time: :desc)

  end

  private
  def filter_params
    params.permit(:baby_id, :assistant_id, :status)
  end

end

app/controllers/api/activities_controller.rb
class Api::ActivitiesController < ApplicationController

  def index
    render json: Activity.all, each_serializer: ActivitySerializer
  end

end

app/controllers/api/activity_logs_controller.rb
class Api::ActivityLogsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def index

    query = ActivityLog.all
    query = query.where(baby_id: params[:baby_id]) if params[:baby_id].present?

    render json: query.includes(:assistant), each_serializer: ActivityLog::ListSerializer

  end

  def create

    new_activity = ActivityLog.new
    new_activity.attributes = save_params

    if new_activity.valid?
      new_activity.save!

      render json: new_activity, serializer: ActivityLog::SingleSerializer, status: :created
    else
      render json: {errors: new_activity.errors.full_messages}, status: :unprocessable_entity
    end

  end

  def update

    activity_log = ActivityLog.find_by(id: params[:id])

    if activity_log.nil?
      return head :not_found
    end

    activity_log.attributes = update_params

    if activity_log.valid?
      activity_log.save!

      render json: activity_log, serializer: ActivityLog::SingleSerializer, status: :ok

    else
      render json: {errors: activity_log.errors.full_messages}, status: :unprocessable_entity
    end

  end

  private
  def save_params
    params.permit(:activity_id, :baby_id, :assistant_id, :start_time)
  end

  def update_params
    # Required to avoid scenario where request only contains comments and allows update
    # of activity log if this has already been previously closed
    default = { stop_time: nil, comments: nil}
    filtered_params = params.permit(:stop_time, :comments)

    default.merge filtered_params
  end

end

app/controllers/api/babies_controller.rb
class Api::BabiesController < ApplicationController

  def index
    render json: Baby.all, each_serializer: BabySerializer
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def not_found_page
  end
end

app/helpers/activity_logs_helper.rb
module ActivityLogsHelper
end

app/helpers/api/activities_helper.rb
module Api::ActivitiesHelper
end

app/helpers/api/activity_logs_helper.rb
module Api::ActivityLogsHelper
end

app/helpers/api/babies_helper.rb
module Api::BabiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activity_logs/index.html.erb
<div class="container">
  <br>
  <div class="row">
    <div class="container">
      <h3> Log de actividades</h3>
    </div>
  </div>

    <form action="activity_logs" method="get">
      <div class="form-row">
        <div class="form-group col-md-3" >
          <label class="control-label">Bebés</label>
          <select name="baby_id" class="form-control">
            <option value="">Seleccionar bebé</option>
            <% @babies.each do |baby| %>
            <option <%= (baby.id.to_s == @filters[:baby_id]) ? 'selected' : '' %> value="<%= baby.id %>"><%= baby.name %></option>
            <% end %>
          </select>
        </div>
        <div class="form-group col-md-3">
          <label class="control-label">Asistentes</label>
          <select name="assistant_id" class="form-control">
            <option value="">Seleccionar asistente</option>
            <% @assistants.each do |assistant| %>
              <option <%= (assistant.id.to_s == @filters[:assistant_id]) ? 'selected' : '' %> value="<%= assistant.id %>"><%= assistant.name %></option>
            <% end %>
          </select>
        </div>
        <div class="form-group col-md-3">
          <label class="control-label">Estatus</label>
          <select name="status" class="form-control">
            <option value="">Todos</option>
            <option <%= ("true" == @filters[:status]) ? 'selected' : '' %> value="true">Terminado</option>
            <option <%= ("false" == @filters[:status]) ? 'selected' : '' %> value="false">En progreso</option>
          </select>
        </div>
        <div class="form-group col-md-3">
          <label class="control-label d-block" >&nbsp;</label>
          <button class="btn btn-primary">Filtrar</button>
        </div>
      </div>
    </form>

  <table class="table ">
    <thead class="thead-light">
    <tr>
      <th>Bebé</th>
      <th>Assistente</th>
      <th>Actividad</th>
      <th>Inicio</th>
      <th>Estatus</th>
      <th>Duración</th>
    </tr>
    </thead>
    <tbody>
      <% @activity_logs.each do |activity_log| %>
        <tr>
          <td ><%= activity_log.baby.name %></td>
          <td ><%= activity_log.assistant.name %></td>
          <td ><%= activity_log.activity.name %></td>
          <td ><%= activity_log.start_time.in_time_zone(@time_zone).strftime("%Y-%m-%d %H:%M") %></td>
          <td ><%= activity_log.stop_time.present? ? "Terminado" : "En progreso" %></td>
          <td ><%= activity_log.duration.present? ? activity_log.duration : "*" %></td>
        </tr>
      <% end %>
      <% if @activity_logs.empty? %>
        <tr>
          <th colspan="6" class="text-center" scope="row">No se encontráron log de actividades</th>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/application/not_found_page.html.erb
<div class="container">
  <div class="row">
    <div class="container text-center">
      <br>
      <h2>Lo sentimos parece que esta pagina no existe.</h2>
      <br>
      <a href=<%= activity_logs_path %>>Regresar al log de actividades</a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KineduTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>